### ISSUE TITLE
Add option to turn off shadows

### ISSUE THREAD

**Issue by Saul2022** [outobugi/Terrain3D#120]
While it good to have shadows for a better looking terrain, the performance can be worst and make a difference

**Comment by Saul2022** [comment]
> Do you want to expose `geometry_instance/cast_shadow` and `VisualInstance3D/layers`?
> 
Yeah, that sounds alright.

**Comment by Calinou** [comment]
It could make sense to support baking a shadow texture for the terrain, although this requires having a fixed DirectionalLight3D angle and will not work on dynamic objects (unless these use a custom shader to sample the shadow texture below them, like in [this game](https://youtu.be/C_36gK1ssVc?t=66)).

**Comment by Saul2022** [comment]
> Using a lower LOD level for shadows by creating a dedicated shadow mesh is also an option, but you need to make sure the shadow mesh's vertices are always "below" the original mesh to avoid self-shadowing artifacts.

Talking about LOD( though it kind off topic), could it be possible to make lod levels affect more the terrain geometry( i don´t mean reducing distance or size), but making  lod pop in more noticeable( ie reducing more polygons), i saw the wireframe stats, and while it decreases them, it doesn´t  save as much performance, so making lods  reduce more geometry than now could help in performance.

**Comment by TokisanGames** [comment]
This issue will be closed soon as it is just exporting some variables. I invite further discussion on terrain shadowing in https://github.com/outobugi/Terrain3D/discussions/133.

> i saw the wireframe stats, and while it decreases them, it doesn´t save as much performance, 

That's because GPUs chew through vertices. It looks like the terrain pumps out 425k triangles at 7 lods/ 48 units, which you'll only see half of when on the ground. At 10/64 it's 1 million. Even old, low end cards can do multi-millions. eg. [9.3M @ 100fps on a GTX680](https://www.reddit.com/r/gamedev/comments/uqj1m/how_many_polygons_can_the_average_gpu_do_at_60fps/)

The performance crunch is in the shader and/or the renderer (including lighting, shadows, and occlusion).

**Comment by Saul2022** [comment]
Even old, low end cards can do multi-millions. eg. [9.3M @ 100fps on a GTX680](https://www.reddit.com/r/gamedev/comments/uqj1m/how_many_polygons_can_the_average_gpu_do_at_60fps/)

True, though it also depends on the engine, for example in godot  there are problems reported by the rendering team about something slowing down the renderer, even on less complex scenes, and also ue5 with  nanite  i can even handle 2 billion triangles at 20 fps  on the lowest quality effects.
