### ISSUE TITLE
Adding new texture to new surface crashes Godot

### ISSUE THREAD

**Issue by GeneralProtectionFault** [outobugi/Terrain3D#147]
Obligatory info:
Godot 4.1.1 mono/C# version
[Terrain3D v0.8.1-alpha_gd4.1.1](https://github.com/outobugi/Terrain3D/releases/tag/v0.8.1-alpha_gd4.1.1)
Windows x64
Nvidia 3060 12 GB VRAM

Created a new project, followed the instructions to incorporate the addon.  New 3D scene & terrain, saved with .res extension.  I tried to add a new surface, and was planning to add an image texture to paint with, but adding an image (and apparently others as well) texture crashes Godot:

![image](https://github.com/outobugi/Terrain3D/assets/29645865/222b7f51-a3b9-46cd-a045-b0f760d4218f)

**Comment by TokisanGames** [comment]
OK. It shouldn't crash. But also images must be a specific format as defined in the docs. Maybe we need to filter that field to limit the options.

**Comment by GeneralProtectionFault** [comment]
Ah ok, I definitely need to check the Wiki, but the crash happened just selecting the new [whatever] texture option from the menu, before even dragging the actual image in.

**Comment by TokisanGames** [comment]
You don't need to select anything from that menu. Just drag the texture into the slot and it will work if it's the right format. If not you'll get an error saying it's not the right format. The wiki describes the format and how to make it.

**Comment by Saul2022** [comment]
To further confirm it happens woth other formats of the  image tab, maybe there could be some way to hide and just have the fast load or load.

**Comment by TokisanGames** [comment]
Fixed.

**Comment by TokisanGames** [comment]
I had to adjust this fix. Previously, I reduced the list of possible options by requiring the format be an ImageTexture. However that only works for DDS files and refuses PNGs. I tried CompressedTexture, but that only works for PNGs and refuses DDSs. So we have to accept the parent class, Texture2D to accept both file types. However I was able to use the hint filter to limit it to CompressedTexture and ImageTexture. Now only those options appear in the list. Neither work to create blanks as people should just load/quickload or drag the files in. And they no longer cause a crash.

Fixed in 1a4b2955021f1623c2115c7d67e8d161994582b9
Adjusted in 41f5456e4f5eb923738b55c66d275194d7e35408
