### ISSUE TITLE
Adding Terrain3D surface Resource godot client just crashes

### ISSUE THREAD

**Issue by YuriLavs** [outobugi/Terrain3D#153]
I downloaded some textures from Poly haven. Imported it in Godot engine. Then Added a surface resource, in albedo picked new image texture. It stutters a bit and then engine crashed. Texture size is 1024x1024.

**Comment by TokisanGames** [comment]
Please provide enough information so we can help you.

Operating system
Version of godot
Which file did you download, version, or did you build from source and commit version?
Did you read the documentation in the wiki and follow the instructions on creating textures?
`New ImageTexture` won't work. You must create your textures elsewhere and then you can load them in to the fields. The crash was fixed in 1a4b2955021f1623c2115c7d67e8d161994582b9 and 41f5456e4f5eb923738b55c66d275194d7e35408.

**Comment by YuriLavs** [comment]
Ok issue is solved, confusion cause There is nothing mentioned in title page about texture setup requirments. Thanks for pointing out there is section in wiki.

**Comment by TokisanGames** [comment]
OK I'll add a note to the readme
